use aoc::y2015::probably_a_fire_hazard_06::do_solve;
use std::io::Error;

fn main() -> Result<(), Error> {
    aoc::with_input(2015, 6, do_solve)
}
